http:
  host: "0.0.0.0"
  port: "8081"
  path: "/flights"
  pathID: "/flights/{ID}"
  
  
american:
  host: "training-american-flights-proxy.us-e2.cloudhub.io"
  port: "80"
  basePath: "/"
  protocol: "HTTP"
  client_id: "d8143303fa7349fda8c1956549ef18cb"
  client_secret: "aaAE60dAD47448E6b0221B2e827c42dD"
  
  
mule:
  version: "4.4.0"
  
anypoint:
  username: "KiYonas"
  password: "MuleMule2023"
  
  
cloudhub:
  enviroment: "Sandbox"
  app: "training4-american-ws-Sherka2"
  bg: "Self"
  worker: "Micro"
  
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"
  

  