http:
  host: "0.0.0.0"
  port: "8081"
  path: "/flights"
  pathID: "/flights/{ID}"
  

mule:
  version: "4.5"
  
anypoint:
  username: "SelfLearn"
  password: "LearnMule#2023"
  
  
cloudhub:
  enviroment: "Sandbox"
  app: "training4-american-ws-S"
  bg: "Student"
  worker: "Micro"
  
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"